# Generated by Django 4.1.7 on 2023-03-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birthdate_user_books_user_is_blocked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
