# Generated by Django 4.1.7 on 2023-03-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_author_book_edition_book_genre_book_isnb_and_more"),
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="books",
            field=models.ManyToManyField(related_name="follow", to="books.book"),
        ),
    ]
