# Generated by Django 4.1.7 on 2023-03-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=17, unique=True)),
                ("title", models.CharField(max_length=150)),
                ("author", models.CharField(max_length=150)),
                ("publisher", models.CharField(max_length=100)),
                ("edition", models.DateField()),
                ("genre", models.CharField(max_length=50, null=True)),
                ("language", models.CharField(max_length=50)),
                ("pages_number", models.IntegerField()),
            ],
        ),
    ]
