# Generated by Django 4.1.7 on 2023-03-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_loaned_copies',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
