# Generated by Django 4.1.7 on 2023-03-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_book_count_loaned_copies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="count_loaned_copies",
            field=models.IntegerField(null=True),
        ),
    ]
