# Generated by Django 4.1.7 on 2023-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="return_date",
            field=models.DateField(),
        ),
    ]
