# Generated by Django 4.1.7 on 2023-03-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_alter_loan_return_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="return_date",
            new_name="expected_return",
        ),
        migrations.AddField(
            model_name="loan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="returned",
            field=models.DateTimeField(blank=True, default="2021-01-01 12:34:56-0500"),
            preserve_default=False,
        ),
    ]
