# Generated by Django 4.1.7 on 2023-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0004_rename_return_date_loan_expected_return_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="returned",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
