# Generated by Django 4.1.7 on 2023-03-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='isbn',
            field=models.CharField(max_length=17),
        ),
    ]
